// 01-basic-web-app/frontend/src/app/modules/accounts/account-details/components/account-details.component.ts
import {Component, EventEmitter, OnInit} from '@angular/core';
import {AccountsService} from "../../../../services/accounts.service";
import {AccountDetailsModel} from "../../../../models/account.models";

@Component({
    selector: 'account-details',
    templateUrl: './account-details.component.html',
    styleUrls: ['./account-details.component.scss']
})
export class AccountDetailsComponent implements OnInit {

    backToDetailsEventEmitter: EventEmitter<any> = new EventEmitter<any>();
    makeOwnTransferEventEmitter: EventEmitter<any> = new EventEmitter<any>();
    makeOwnDepositEventEmitter: EventEmitter<any> = new EventEmitter<any>();

    accountDetails: AccountDetailsModel;

    private accountNumber: string;

    constructor(private _accountsService: AccountsService) {
    }

    setContext(accountNumber: string) {
        this.accountNumber = accountNumber;
    }

    async ngOnInit() {
        this.accountDetails = await this._accountsService.getAccountDetails(this.accountNumber);
    }

    onGoBackClicked() {
        this.backToDetailsEventEmitter.emit();
    }

    onMakeOwnTransferClicked() {
        this.makeOwnTransferEventEmitter.emit();
    }

    onMakeOwnDepositClicked() {
        this.makeOwnDepositEventEmitter.emit();
    }
}

<div class="container overflow-hidden">
    <div class="row gy-2">
        <div class="col-6">
            <div class="form-group">
                <label for="accountNameId" class="fw-bold">Account name</label>
                <p id="accountNameId">
                    {{ accountDetails?.accountName }}
                </p>
            </div>
        </div>
        <div class="col-6">
            <div class="form-group">
                <label for="accountNumberId" class="fw-bold">Account number</label>
                <p id="accountNumberId">
                    {{ accountDetails?.accountNumber }}
                </p>
            </div>
        </div>
        <div class="col-6">
            <div class="form-group">
                <label for="accountTypeId" class="fw-bold">Account type</label>
                <p id="accountTypeId">
                    {{ accountDetails?.type }}
                </p>
            </div>
        </div>
        <div class="col-6">
            <div class="form-group">
                <label for="balanceId" class="fw-bold">Balance</label>
                <p id="balanceId">{{ accountDetails?.currentBalance | currency:'G' }}</p>
            </div>
        </div>
    </div>
    <div class="row gy-4 margin-bottom-2em">
        <div class="col-3">
            <button id="backButton"
                    type="button"
                    class="btn btn-secondary"
                    (click)="onGoBackClicked()"
            >Back to list</button>
        </div>
        <div class="col-6"></div>
        <div class="col-3">
            <button id="ownTransferButton"
                    type="button"
                    class="btn btn-primary float-right"
                    (click)="onMakeOwnTransferClicked()"
            >Own transfer</button>
        </div>
    </div>
    <div class="row gy-4">
        <div class="col-12">
            <transactions-history [transactionsHistory]="accountDetails?.transactionsList"></transactions-history>
        </div>
    </div>
</div>

// ui/react/src/modules/accounts/AccountDetails.tsx
import {AccountDetailsModel} from "../../models/account.models";
import {TransactionHistory} from "../transactions/TransactionHistory";
import {useEffect, useState} from "react";
import {useNavigate, useParams} from "react-router-dom";
import AccountsService from "../../services/accounts.service";

export function AccountDetails() {

    const {accountNumber} = useParams();
    const [accountDetails, setAccountDetails] = useState<AccountDetailsModel>();
    const navigate = useNavigate();

    useEffect(() => {
        if (accountNumber) {
            AccountsService.getAccountDetails(accountNumber).then(resp => {
                setAccountDetails(resp.data);
            })
        } else {
            setAccountDetails(undefined);
        }
    }, [accountNumber]);

    const onGoBackClicked = () => {
        navigate('/ui/accounts');
    }

    const onMakeOwnDepositClicked = () => {

    }

    const onMakeOwnTransferClicked = () => {

    }

    return (
        <>
            <div className="container overflow-hidden">
                <div className="row gy-2">
                    <div className="col-6">
                        <div className="form-group">
                            <label htmlFor="accountNameId" className="fw-bold">Account name</label>
                            <p id="accountNameId">
                                {accountDetails?.accountName}
                            </p>
                        </div>
                    </div>
                    <div className="col-6">
                        <div className="form-group">
                            <label htmlFor="accountNumberId" className="fw-bold">Account number</label>
                            <p id="accountNumberId">
                                {accountDetails?.accountNumber}
                            </p>
                        </div>
                    </div>
                    <div className="col-6">
                        <div className="form-group">
                            <label htmlFor="accountTypeId" className="fw-bold">Account type</label>
                            <p id="accountTypeId">
                                {accountDetails?.type}
                            </p>
                        </div>
                    </div>
                    <div className="col-6">
                        <div className="form-group">
                            <label htmlFor="balanceId" className="fw-bold">Balance</label>
                            <p id="balanceId">{accountDetails?.currentBalance}G</p>
                        </div>
                    </div>
                </div>
                <div className="row gy-4 margin-bottom-2em">
                    <div className="col-3">
                        <button id="backButton"
                                type="button"
                                className="btn btn-secondary"
                                onClick={onGoBackClicked}
                        >Back to list
                        </button>
                    </div>
                    <div className="col-3"></div>
                    <div className="col-3">
                        <button id="ownDepositButton"
                                type="button"
                                className="btn btn-primary float-right"
                                onClick={onMakeOwnDepositClicked}
                        >Own deposit
                        </button>
                    </div>
                    <div className="col-3">
                        <button id="ownTransferButton"
                                type="button"
                                className="btn btn-primary float-right"
                                onClick={onMakeOwnTransferClicked}
                        >Own transfer
                        </button>
                    </div>
                </div>
                {
                    accountDetails ?
                        <div className="row gy-4">
                            <div className="col-12">
                                <TransactionHistory transactionHistory={accountDetails.transactionsList}/>
                            </div>
                        </div> :
                        <></>
                }
            </div>
        </>
    );
}
