// ui/react/src/modules/deposit/OwnDeposit.tsx
import {AccountModel} from "../../models/account.models";

export interface OwnDepositProps {
    accountNumber: string
}

export function OwnDeposit({accountNumber}: OwnDepositProps) {

    let dstAccountList: Array<AccountModel> = [];

    const onCancelClicked = () => {

    }
    const onDepositClicked = () => {

    }

    return (
        <form>
            <div className="container overflow-hidden">
                <div className="row gy-2">
                    <h5 className="card-title">Own deposit</h5>
                </div>
                <div className="row gy-2">
                    <div className="col-7">
                        <div className="container">
                            <div className="row">
                                <div className="form-group">
                                    <label htmlFor="dstAccountId">To account:</label>
                                    <select id="dstAccountId"
                                            className="form-select"
                                            aria-label="To account"
                                    >
                                        {dstAccountList.map(account =>
                                            <option
                                                selected={accountNumber === account.accountNumber}
                                                value={account.accountNumber}>
                                                {account.accountName}
                                                {account.accountNumber}
                                                {account.currentBalance}G
                                            </option>)}
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="col-5">
                        <div className="container">
                            <div className="row">
                                <div className="col-8">
                                    <div className="form-group">
                                        <label htmlFor="amountId">Amount</label>
                                        <input
                                            type="number"
                                            step='0.01'
                                            placeholder='0.00'
                                            className="form-control"
                                            id="amountId"/>
                                    </div>

                                </div>
                                <div className="col-4">
                                    <div className="form-group">
                                        <label htmlFor="currencyId">Currency</label>
                                        <input
                                            type="text"
                                            className="form-control"
                                            id="currencyId"/>
                                    </div>
                                </div>
                            </div>
                            <div className="row">
                                <div className="col-12">
                                    <div className="form-group">
                                        <label htmlFor="descriptionId">Comment</label>
                                        <input
                                            type="text"
                                            className="form-control"
                                            id="descriptionId"/>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="col-3">
                        <button id="depositCancelButton"
                                type="button"
                                className="btn btn-secondary"
                                onClick={onCancelClicked}
                        >Cancel
                        </button>
                    </div>
                    <div className="col-6"></div>
                    <div className="col-3">
                        <button type="submit"
                                className="btn btn-primary float-right"
                                id="depositButton"
                                onClick={onDepositClicked}
                        >Deposit
                        </button>
                    </div>
                </div>
            </div>
        </form>
    );
}

// ui/angular/src/app/modules/deposit/own-deposit/components/own-deposit.component.ts
import {Component, EventEmitter, OnInit} from '@angular/core';
import {AccountModel} from "../../../../models/account.models";
import {FormControl, FormGroup, Validators} from "@angular/forms";
import {CurrencyEnum} from "../../../../models/enums";
import {EregoldUserContext} from "../../../../context/eregold-user-context";
import {TransactionsService} from "../../../../services/transactions.service";
import {ServiceDispatcher} from "../../../../core/service-dispatcher/service-dispatcher";

@Component({
    selector: 'own-deposit',
    templateUrl: './own-deposit.component.html',
    styleUrls: ['./own-deposit.component.scss']
})
export class OwnDepositComponent implements OnInit {
    backEventEmitter: EventEmitter<any> = new EventEmitter<any>();

    dstAccountList: Array<AccountModel>;

    formGroup: FormGroup = new FormGroup({
        dstAccount: new FormControl('', Validators.required),
        description: new FormControl('Deposit', Validators.required),
        amount: new FormControl(null, Validators.required), // TODO regex to match 2 decimal places
        currency: new FormControl({
            value: CurrencyEnum.GLD,
            disabled: true
        })
    });

    private destAccountNumber: string;
    private allAccountsList: Array<AccountModel>;

    constructor(private _userContext: EregoldUserContext,
                private _transactionsService: TransactionsService) {
    }

    setContext(accountNumber: string) {
        this.destAccountNumber = accountNumber;
    }

    async ngOnInit() {
        this.allAccountsList = await this._userContext.getAccounts();
        this.dstAccountList = this.allAccountsList;

        if (this.destAccountNumber) {
            this.formGroup.get('dstAccount').setValue(this.destAccountNumber);
            this.formGroup.get('dstAccount').disable();
        }
    }

    onCancelClicked() {
        this.backEventEmitter.emit();
    }

    onDepositClicked() {
        if (this.formGroup.valid) {
            ServiceDispatcher.dispatch(this._transactionsService.deposit(this.formGroup.getRawValue())).then(async () => {
                await this._userContext.getAccounts(true);
                this.backEventEmitter.emit();
            });
        }
    }
}

<form [formGroup]="formGroup">
    <div class="container overflow-hidden">
        <div class="row gy-2">
            <h5 class="card-title">Own deposit</h5>
        </div>
        <div class="row gy-2">
            <div class="col-7">
                <div class="container">
                    <div class="row">
                        <div class="form-group">
                            <label for="dstAccountId">To account:</label>
                            <select id="dstAccountId"
                                    class="form-select"
                                    aria-label="To account"
                                    formControlName="dstAccount"
                            >
                                <ng-container *ngFor="let account of dstAccountList">
                                    <option [value]="account.accountNumber">
                                        {{ account.accountName }}
                                        {{ account.accountNumber}}
                                        {{ account.currentBalance | currency:'G' }}
                                    </option>
                                </ng-container>
                            </select>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-5">
                <div class="container">
                    <div class="row">
                        <div class="col-8">
                            <div class="form-group">
                                <label for="amountId">Amount</label>
                                <input
                                        [class.is-invalid]="formGroup.get('amount')?.invalid"
                                        formControlName="amount"
                                        type="number"
                                        step='0.01'
                                        placeholder='0.00'
                                        class="form-control"
                                        id="amountId">
                            </div>

                        </div>
                        <div class="col-4">
                            <div class="form-group">
                                <label for="currencyId">Currency</label>
                                <input
                                        [class.is-invalid]="formGroup.get('currency')?.invalid"
                                        formControlName="currency"
                                        type="text"
                                        class="form-control"
                                        id="currencyId">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <div class="form-group">
                                <label for="descriptionId">Comment</label>
                                <input
                                        [class.is-invalid]="formGroup.get('description')?.invalid"
                                        formControlName="description"
                                        type="text"
                                        class="form-control"
                                        id="descriptionId">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-3">
                <button id="depositCancelButton"
                        type="button"
                        class="btn btn-secondary"
                        (click)="onCancelClicked()"
                >Cancel
                </button>
            </div>
            <div class="col-6"></div>
            <div class="col-3">
                <button type="submit"
                        class="btn btn-primary float-right"
                        id="depositButton"
                        (click)="onDepositClicked()"
                        [disabled]="formGroup.invalid"
                >Deposit
                </button>
            </div>
        </div>
    </div>
</form>
