// ui/react/src/modules/accounts/AccountsList.tsx
import {AccountModel} from "../../models/account.models";
import {useNavigate} from "react-router-dom";
import EregoldUserContext from "../../context/eregold-user-context";
import {useContext} from "react";

export function AccountsList() {
    const navigate = useNavigate();

    const { accounts } = useContext(EregoldUserContext);

    const onDetailsClicked = (accountNumber: string) => {
        navigate('/ui/account/' + accountNumber);
    }

    const onMakeOwnTransferClicked = () => {

    }

    const onMakeOwnDepositClicked = () => {
        navigate('/ui/deposit');
    }

    const onAddAccountClicked = () => {

    }

    const accountsList = accounts.map((account: AccountModel) =>
        <tr key={account.accountNumber}>
            <td>{account?.accountName}</td>
            <td>{account?.accountNumber}</td>
            <td>{account?.currentBalance}G</td>
            <td>{account?.type}</td>
            <td>
                <button type="button" className="btn btn-outline-secondary"
                        onClick={() => onDetailsClicked(account?.accountNumber)}>
                    <i className="bi bi-box-arrow-right"></i>
                </button>
            </td>
        </tr>
    )

    return (
        <>
            <table className="table">
                <thead>
                <tr>
                    <th scope="col">Account name</th>
                    <th scope="col">Account number</th>
                    <th scope="col">Current balance</th>
                    <th scope="col">Type</th>
                    <th scope="col"></th>
                </tr>
                </thead>
                <tbody>
                {accountsList}
                </tbody>
            </table>

            <button type="button"
                    className="btn btn-secondary me-2"
                    onClick={onMakeOwnTransferClicked}
            >Own transfer
            </button>
            <button type="button"
                    className="btn btn-secondary"
                    onClick={onMakeOwnDepositClicked}
            >Own deposit
            </button>
            <button type="button"
                    className="btn btn-primary float-end"
                    id="addAccountButton"
                    onClick={onAddAccountClicked}
            >Add account
            </button>

        </>
    );
}

// 01-basic-web-app/frontend/src/app/modules/accounts/accounts-list/components/accounts-list.component.ts
import {Component, EventEmitter, OnInit} from '@angular/core';
import {AccountModel} from "../../../../models/account.models";
import {EregoldUserContext} from "../../../../context/eregold-user-context";

@Component({
    selector: 'accounts-list',
    templateUrl: './accounts-list.component.html',
    styleUrls: ['./accounts-list.component.scss']
})
export class AccountsListComponent implements OnInit {

    createAccountEventEmitter: EventEmitter<any> = new EventEmitter();
    showDetailsEventEmitter: EventEmitter<string> = new EventEmitter<string>();
    accountsList: Array<AccountModel>;

    constructor(private _userContext: EregoldUserContext) {
    }

    async ngOnInit() {
        this.accountsList = await this._userContext.getAccounts();
    }

    onDetailsClicked(accountNumber: string) {
        this.showDetailsEventEmitter.emit(accountNumber);
    }

    onAddAccountClicked() {
        this.createAccountEventEmitter.emit();
    }
}

<table class="table">
    <thead>
    <tr>
        <th scope="col">Account name</th>
        <th scope="col">Account number</th>
        <th scope="col">Current balance</th>
        <th scope="col">Currency</th>
        <th scope="col">Type</th>
        <th scope="col"></th>
    </tr>
    </thead>
    <tbody>
    <ng-container *ngIf="accountsList">
        <ng-container *ngFor="let account of accountsList">
            <tr>
                <td>{{account?.accountName}}</td>
                <td>{{account?.accountNumber}}</td>
                <td>{{account?.currentBalance}}</td>
                <td>{{account?.currency}}</td>
                <td>{{account?.type}}</td>
                <td>
                    <button type="button" class="btn btn-outline-secondary"
                            (click)="onDetailsClicked(account?.accountNumber)">
                        <i class="bi bi-box-arrow-right"></i>
                    </button>
                </td>
            </tr>
        </ng-container>
    </ng-container>
    </tbody>
</table>

<button type="button"
        class="btn btn-secondary"
        (click)="onMakeOwnTransferClicked()"
>Own transfer
</button>
<button type="button"
        class="btn btn-primary float-right"
        id="addAccountButton"
        (click)="onAddAccountClicked()"
>Add account
</button>
