// 01-basic-web-app/frontend/src/app/modules/transfer/own-transfer/components/own-transfer.component.ts
import {Component, EventEmitter, OnInit} from '@angular/core';
import {EregoldUserContext} from "../../../../context/eregold-user-context";
import {AccountModel} from "../../../../models/account.models";
import {FormControl, FormGroup, Validators} from "@angular/forms";
import {TransactionsService} from "../../../../services/transactions.service";
import {CurrencyEnum} from "../../../../models/enums";

@Component({
    selector: 'own-transfer',
    templateUrl: './own-transfer.component.html',
    styleUrls: ['./own-transfer.component.scss']
})
export class OwnTransferComponent implements OnInit {

    backEventEmitter: EventEmitter<any> = new EventEmitter<any>();

    srcAccountList: Array<AccountModel>;
    dstAccountList: Array<AccountModel>;

    formGroup: FormGroup = new FormGroup({
        srcAccount: new FormControl('', Validators.required),
        dstAccount: new FormControl('', Validators.required),
        description: new FormControl('', Validators.required),
        amount: new FormControl(null, Validators.required), // TODO regex to match 2 decimal places
        currency: new FormControl({
            value: CurrencyEnum.GLD,
            disabled: true
        })
    });

    private initialAccountNumber: string;
    private allAccountsList: Array<AccountModel>;

    constructor(private _userContext: EregoldUserContext,
                private _transactionsService: TransactionsService) {
    }

    setContext(accountNumber: string) {
        this.initialAccountNumber = accountNumber;
    }

    async ngOnInit() {
        this.allAccountsList = await this._userContext.getAccounts();
        this.srcAccountList = this.allAccountsList;
        this.dstAccountList = this.allAccountsList;

        this.initFormGroupHandlers();
        if (this.initialAccountNumber) {
            this.formGroup.get('srcAccount').setValue(this.initialAccountNumber);
        }
    }

    onCancelClicked() {
        this.backEventEmitter.emit();
    }

    onTransferClicked() {
        if (this.formGroup.valid) {
            this._transactionsService.transfer(this.formGroup.getRawValue()).subscribe(async () => {
                await this._userContext.getAccounts(true);
                this.backEventEmitter.emit();
            });
        }
    }

    private initFormGroupHandlers() {
        this.formGroup.get('srcAccount').valueChanges.subscribe(chosenAcc => {
            this.dstAccountList = this.allAccountsList.filter(account => account.accountNumber !== chosenAcc)
            if (this.dstAccountList.length > 0) {
                this.formGroup.get('dstAccount').setValue(this.dstAccountList[0].accountNumber);
            }
        });
    }
}

<form [formGroup]="formGroup">
    <div class="container overflow-hidden">
        <div class="row gy-2">
            <h5 class="card-title">Own transfer</h5>
        </div>
        <div class="row gy-2">
            <div class="col-7">
                <div class="container">
                    <div class="row">
                        <div class="form-group">
                            <label for="srcAccountId">From account:</label>
                            <select id="srcAccountId"
                                    class="form-select"
                                    aria-label="From account"
                                    [formControlName]="controlNames.SRC_ACCOUNT"
                            >
                                <ng-container *ngFor="let account of srcAccountList">
                                    <option [ngValue]="account">
                                        {{ account.accountName }}
                                        {{ account.accountNumber}}
                                        {{ account.currentBalance | currency:'G' }}
                                    </option>
                                </ng-container>
                            </select>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group">
                            <label for="dstAccountId">To account:</label>
                            <select id="dstAccountId"
                                    class="form-select"
                                    aria-label="To account"
                                    [formControlName]="controlNames.DST_ACCOUNT"
                            >
                                <ng-container *ngFor="let account of dstAccountList">
                                    <option [ngValue]="account">
                                        {{ account.accountName }}
                                        {{ account.accountNumber}}
                                        {{ account.currentBalance | currency:'G' }}
                                    </option>
                                </ng-container>
                            </select>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-5">
                <div class="container">
                    <div class="row">
                        <div class="col-8">
                            <div class="form-group">
                                <label for="amountId">Amount</label>
                                <input
                                        [class.is-invalid]="formGroup.get(controlNames.AMOUNT)?.invalid"
                                        [formControlName]="controlNames.AMOUNT"
                                        type="number"
                                        step='0.01'
                                        placeholder='0.00'
                                        class="form-control"
                                        id="amountId">
                                <div *ngIf="formGroup.get(controlNames.AMOUNT)?.errors?.['amountExceedsBalance']" class="invalid-feedback">
                                    Provided amount exceeds the available balance.
                                </div>
                            </div>
                        </div>
                        <div class="col-4">
                            <div class="form-group">
                                <label for="currencyId">Currency</label>
                                <input
                                        [class.is-invalid]="formGroup.get(controlNames.CURRENCY)?.invalid"
                                        [formControlName]="controlNames.CURRENCY"
                                        type="text"
                                        class="form-control"
                                        id="currencyId">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <div class="form-group">
                                <label for="descriptionId">Comment</label>
                                <input
                                        [class.is-invalid]="formGroup.get(controlNames.DESCRIPTION)?.invalid"
                                        [formControlName]="controlNames.DESCRIPTION"
                                        type="text"
                                        class="form-control"
                                        id="descriptionId">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-3">
                <button id="transferCancelButton"
                        type="button"
                        class="btn btn-secondary"
                        (click)="onCancelClicked()"
                >Cancel
                </button>
            </div>
            <div class="col-6"></div>
            <div class="col-3">
                <button type="submit"
                        class="btn btn-primary float-right"
                        id="transferButton"
                        (click)="onTransferClicked()"
                        [disabled]="formGroup.invalid"
                >Transfer
                </button>
            </div>
        </div>
    </div>
</form>

// ui/react/src/modules/transfer/OwnTransfer.tsx
import {useNavigate, useParams} from "react-router-dom";
import {z} from "zod";
import {FieldValues, useForm} from "react-hook-form";
import {zodResolver} from "@hookform/resolvers/zod";
import EregoldUserContext from "../../context/eregold-user-context";
import {ChangeEvent, useContext, useState} from "react";
import {AccountModel} from "../../models/account.models";
import {CurrencyEnum} from "../../models/enums";
import TransactionsService from "../../services/transactions.service";

const ownTransferSchema = z.object({
    srcAccount: z.string().length(18),
    dstAccount: z.string().length(18),
    description: z.string().min(3),
    amount: z.string().refine((val) => !Number.isNaN(parseInt(val, 10)), {
        message: "Expected number, received a string"
    }),
    currency: z.string().min(1),
})

type TransferFormData = z.infer<typeof ownTransferSchema>;

interface OwnTransferFormConfig {
    srcAccountList: Array<AccountModel>;
    dstAccountList: Array<AccountModel>;
    initialSrcAccount: string;
    initialDstAccount: string;
}

export function OwnTransfer() {
    const navigate = useNavigate();
    const {accounts, reloadAccounts} = useContext(EregoldUserContext);
    const {accountNumber} = useParams();

    const initialFormConfig: OwnTransferFormConfig = {} as OwnTransferFormConfig;
    initialFormConfig.srcAccountList = [...accounts];

    if (accountNumber) {
        initialFormConfig.initialSrcAccount = accountNumber;
    } else {
        initialFormConfig.initialSrcAccount = accounts[0].accountNumber;
    }

    initialFormConfig.dstAccountList = accounts.filter(acc => acc.accountNumber !== initialFormConfig.initialSrcAccount);
    initialFormConfig.initialDstAccount = initialFormConfig.dstAccountList.length > 0 ? initialFormConfig.dstAccountList[0].accountNumber : "";

    const [formConfig, setFormConfig] = useState<OwnTransferFormConfig>(initialFormConfig);
    const currencyOption = CurrencyEnum.GLD; // Only single option right now

    /* TODO fix this validation */
    ownTransferSchema.refine((data) => {
            if (formConfig) {
                const selectedAccount = formConfig.srcAccountList.find(acc => acc.accountNumber === data.srcAccount);
                if (selectedAccount) {
                    return (selectedAccount.currentBalance - Number(data.amount)) >= 0;
                }
            }
            return true;
        },
        {
            message: "Amount exceeds available balance",
            path: ["amount"],
        });

    const {
        register,
        handleSubmit,
        control,
        setValue,
        formState: {errors}
    } = useForm<TransferFormData>({resolver: zodResolver(ownTransferSchema)});

    const onCancelClicked = () => {
        navigate(-1);
    };

    const onTransferClicked = (data: FieldValues) => {
        TransactionsService.transfer(data).then(resp => {
            reloadAccounts();
            navigate(-1);
        });
    }

    const onSrcAccountSelected = (event: ChangeEvent<HTMLSelectElement>) => {
        const accountNumber = event.target.value;
        const currentFormConfig = {...formConfig} as OwnTransferFormConfig;
        currentFormConfig.dstAccountList = accountNumber ? accounts.filter(acc => acc.accountNumber !== accountNumber) : [...accounts];
        currentFormConfig.initialSrcAccount = accountNumber;
        if (currentFormConfig.dstAccountList.length === 1) {
            setValue('dstAccount', currentFormConfig.dstAccountList[0].accountNumber);
        }
        setFormConfig(currentFormConfig);
    }

    return (
        <form onSubmit={handleSubmit(onTransferClicked)}>
            <div className="container overflow-hidden">
                <div className="row gy-2">
                    <h5 className="card-title">Own transfer</h5>
                </div>
                <div className="row gy-2">
                    <div className="col-7">
                        <div className="container">
                            <div className="row">
                                <div className="form-group">
                                    <label htmlFor="srcAccountId">From account:</label>
                                    <select id="srcAccountId"
                                            {...register('srcAccount')}
                                            className="form-select"
                                            aria-label="From account"
                                            onChange={onSrcAccountSelected}
                                            value={formConfig?.initialSrcAccount}
                                    >
                                        {
                                            formConfig?.srcAccountList.map(account =>
                                                <option key={account.accountNumber} value={account.accountNumber}>
                                                    {account.accountName + ' '}
                                                    {account.accountNumber + ' '}
                                                    {account.currentBalance}G
                                                </option>
                                            )
                                        }
                                    </select>
                                    {errors.srcAccount &&
                                        <p className="alert alert-danger">{errors.srcAccount.message}</p>}
                                </div>
                            </div>
                            <div className="row">
                                <div className="form-group">
                                    <label htmlFor="dstAccountId">To account:</label>
                                    <select id="dstAccountId"
                                            {...register('dstAccount')}
                                            className="form-select"
                                            aria-label="To account"
                                            value={
                                                formConfig?.initialDstAccount
                                            }
                                    >
                                        {
                                            formConfig?.dstAccountList.map(account =>
                                                <option key={account.accountNumber} value={account.accountNumber}>
                                                    {account.accountName + ' '}
                                                    {account.accountNumber + ' '}
                                                    {account.currentBalance}G
                                                </option>
                                            )
                                        }
                                    </select>
                                    {errors.dstAccount &&
                                        <p className="alert alert-danger">{errors.dstAccount.message}</p>}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="col-5">
                        <div className="container">
                            <div className="row">
                                <div className="col-8">
                                    <div className="form-group">
                                        <label htmlFor="amountId">Amount</label>
                                        <input
                                            {...register('amount')}
                                            type="number"
                                            step='0.01'
                                            placeholder='0.00'
                                            className="form-control"
                                            id="amountId"/>
                                        {errors.amount &&
                                            <p className="alert alert-danger">{errors.amount.message}</p>}
                                    </div>
                                </div>
                                <div className="col-4">
                                    <div className="form-group">
                                        <label htmlFor="currencyId">Currency</label>
                                        <input
                                            {...register('currency')}
                                            value={currencyOption}
                                            type="text"
                                            className="form-control"
                                            id="currencyId"/>
                                        {errors.currency &&
                                            <p className="alert alert-danger">{errors.currency.message}</p>}
                                    </div>
                                </div>
                            </div>
                            <div className="row">
                                <div className="col-12">
                                    <div className="form-group">
                                        <label htmlFor="descriptionId">Comment</label>
                                        <input
                                            {...register('description')}
                                            type="text"
                                            className="form-control"
                                            id="descriptionId"/>
                                        {errors.description &&
                                            <p className="alert alert-danger">{errors.description.message}</p>}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="col-3">
                        <button id="transferCancelButton"
                                type="button"
                                className="btn btn-secondary"
                                onClick={onCancelClicked}
                        >Cancel
                        </button>
                    </div>
                    <div className="col-6"></div>
                    <div className="col-3">
                        <button type="submit"
                                className="btn btn-primary float-right"
                                id="transferButton"
                        >Transfer
                        </button>
                    </div>
                </div>
            </div>
        </form>
    );
}
