// 01-basic-web-app/frontend/src/app/modules/dashboard/components/dashboard.component.ts
import {Component, OnInit} from '@angular/core';
import {UserContext} from "../../common/user.context";
import {Router} from "@angular/router";

@Component({
    selector: 'dashboard',
    templateUrl: './dashboard.component.html',
    styleUrls: ['./dashboard.component.scss']
})
export class DashboardComponent implements OnInit {

    constructor(private _userContext: UserContext,
                private _router: Router) {
    }

    ngOnInit(): void {
        if (!this._userContext.isLoggedIn) {
            this._router.navigate(['login']);
        }
    }

}

<top-bar></top-bar>
<div class="container">
    <div class="row mt-5">
        <div class="col-2"></div>
        <div class="col-8">
            <div class="card shadow">
                <div class="card-body">
                    <div class="row">
                        <div class="col-12">
                            <dynamic-component-manager #componentManager></dynamic-component-manager>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-2"></div>
    </div>
</div>

// ui/react/src/modules/dashboard/Dashboard.tsx
import {TopBar} from "../top-bar/TopBar";
import {DashboardCard} from "./DashboardCard";
import {Outlet, useNavigate} from "react-router-dom";
import userContext from "../../context/user-context";

export function Dashboard() {
    const navigate = useNavigate();

    if (!userContext.isLoggedIn) {
        navigate('login');
    }

    return (
        <>
            <TopBar/>
            <DashboardCard>
                <Outlet/>
            </DashboardCard>
        </>
    );
}
